### ISSUE TITLE
TypeError during commit

### ISSUE THREAD

**Issue by alanorth** [ilri/OpenRXV#119]
I see this sometimes and I don't know what causes it:

```console
[Nest] 88   - 08/26/2021, 5:17:26 PM   [HarvesterService] reindex function is called
[Nest] 88   - 08/26/2021, 5:17:26 PM   [HarvesterService] updateAliases final to temp
[Nest] 88   - 08/26/2021, 5:17:27 PM   [HarvesterService] Delete final
[Nest] 88   - 08/26/2021, 5:17:27 PM   [HarvesterService] Create final
[Nest] 88   - 08/26/2021, 5:18:20 PM   [HarvesterService] Reindex to final
[Nest] 88   - 08/26/2021, 5:18:20 PM   [HarvesterService] updateAliases temp to final
[Nest] 88   - 08/26/2021, 5:18:20 PM   [DSpaceAltmetrics] ResponseError: search_phase_execution_exception +47ms
(node:88) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'body' of undefined
    at getMoreUntilDone (/backend/dist/plugins/dspace_altmetrics/index.js:112:45)
    at getMoreUntilDone (/backend/dist/plugins/dspace_altmetrics/index.js:127:25)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:88) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 70)
(node:88) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[Nest] 88   - 08/26/2021, 5:18:20 PM   [DSpaceAltmetrics] ResponseError: search_phase_execution_exception +2ms
(node:88) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'body' of undefined
    at getMoreUntilDone (/backend/dist/plugins/dspace_altmetrics/index.js:112:45)
    at getMoreUntilDone (/backend/dist/plugins/dspace_altmetrics/index.js:127:25)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:88) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 71)
[Nest] 88   - 08/26/2021, 5:18:21 PM   [HarvesterService] Delete temp
[Nest] 88   - 08/26/2021, 5:18:21 PM   [HarvesterService] Create temp
[Nest] 88   - 08/26/2021, 5:18:21 PM   [HarvesterService] Indexing finished
```

The error comes when I commit indexing. I see this error in the backend/api logs. The commit seems successful nevertheless.

**Comment by alanorth** [comment]
After merging #185 I have not seen this error during index commit. Closing.
