### ISSUE TITLE
Error during commit

### ISSUE THREAD

**Issue by alanorth** [ilri/OpenRXV#177]
I'm regularly seeing this error in the backend log when committing the results of a harvest.

```console
[Nest] 1   - 07/12/2023, 4:46:47 AM   [DSpaceAltmetrics] {"error":{"root_cause":[{"type":"search_context_missing_exception","reason":"No search context found for id [55086]"}],"type":"search_phase_execution_exception","reason":"all shards failed","phase":"query","grouped":true,"failed_shards":[{"shard":-1,"index":null,"reason":{"type":"search_context_missing_exception","reason":"No search context found for id [55086]"}}],"caused_by":{"type":"search_context_missing_exception","reason":"No search context found for id [55086]"}},"status":404} +66ms
/backend/dist/plugins/dspace_altmetrics/index.js:116
                    const handleID = response.body.hits.hits.map((d) => {
                                              ^

TypeError: Cannot read properties of undefined (reading 'body')
    at getMoreUntilDone (/backend/dist/plugins/dspace_altmetrics/index.js:116:47)
    at getMoreUntilDone (/backend/dist/plugins/dspace_altmetrics/index.js:131:25)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

Node.js v18.16.1
```

**Comment by alanorth** [comment]
Duplicate of #119.
